version: "3.4"
services:
  client-certificator:
    environment:
      - CA_EXPIRE=${EXPIRY}
      - CA_SUBJECT=${SUBJECT}
      - SSL_EXPIRE=${EXPIRY}
    image: paulczar/omgwtfssl:v0.1.0
    volumes:
      - ${CLIENT_CERT_FOLDER}:/certs
  server-certificator:
    image: paulczar/omgwtfssl:v0.1.0
    environment:
      - CA_EXPIRE=${EXPIRY}
      - CA_SUBJECT=${SUBJECT}
      - SSL_EXPIRE=${EXPIRY}
      - SSL_DNS=${DNSS}
      - SSL_IP=${IPS}
      - SSL_KEY=/server/key.pem
      - SSL_CERT=/server/cert.pem
    volumes:
      - ${CLIENT_CERT_FOLDER}:/certs
      - ${SERVER_CERT_FOLDER}:/server

